### ISSUE TITLE
URL 클래스 구현

### ISSUE THREAD

**Issue by JooYoung-23** [Jeongyounghyeon/webserv#12]
### URI Class의 목적
- URI 정보 관리의 주체
- 정확한 리소스 식별
- 유효성 검사
  - [HTTP]와 [URI]의 ABNF 룰을 준수한다.
  - [HTTP]와 http-uri 스키마가 요구하는 규칙을 준수한다.
- 리소스 정보 관리의 주체인가?
---
### DONE
- [x] URL Class 선언
- [x] 자료구조 정의 
- - -
### TODO
- [ ] Request URI 파싱 알고리즘 구현
- [ ] Request URI 유효성 검사
- [ ] Reconstructing The Target URL (Section of 3.3 [HTTP/1.1])
- [ ] ServerConfigure 정보 관리
